# Generated by Django 2.1.2 on 2018-10-19 15:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quests', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='modelvisual',
            name='url',
            field=models.URLField(default='', max_length=500),
            preserve_default=False,
        ),
    ]
