# Generated by Django 2.1.2 on 2018-10-19 15:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quests', '0002_modelvisual_url'),
    ]

    operations = [
        migrations.AddField(
            model_name='modelvisual',
            name='scales',
            field=models.CharField(default='1 1 1', max_length=50),
        ),
        migrations.AlterField(
            model_name='modelvisual',
            name='model',
            field=models.FileField(blank=True, null=True, upload_to='media'),
        ),
    ]
